<?php return array(
    'root' => array(
        'name' => 'laravel/laravel',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '38491c5d5a2ad47452fea00e700f34964f13e48d',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'andrey-helldar/laravel-lang-publisher' => array(
            'pretty_version' => 'v4.3.0',
            'version' => '4.3.0.0',
            'reference' => 'ffe8b46ee7c2859279e986353de145cf53f09160',
            'type' => 'library',
            'install_path' => __DIR__ . '/../andrey-helldar/laravel-lang-publisher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'andrey-helldar/pretty-array' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '641c32b19665cc4717906eea6d36c44fb90befa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../andrey-helldar/pretty-array',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'andrey-helldar/support' => array(
            'pretty_version' => 'v1.20.2',
            'version' => '1.20.2.0',
            'reference' => '750374a1e1265fe8d3fe4cb372edad979185dcd9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../andrey-helldar/support',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'artesaos/seotools' => array(
            'pretty_version' => 'v0.22.0',
            'version' => '0.22.0.0',
            'reference' => '55746e0870d3bb6507479bd846d5528c46a7312e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../artesaos/seotools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'asm89/stack-cors' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'b9c31def6a83f84b4d4a40d35996d375755f0e08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-ide-helper' => array(
            'pretty_version' => 'v2.7.0',
            'version' => '2.7.0.0',
            'reference' => '5f677edc14bdcfdcac36633e6eea71b2728a4dbc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-ide-helper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'barryvdh/reflection-docblock' => array(
            'pretty_version' => 'v2.0.6',
            'version' => '2.0.6.0',
            'reference' => '6b69015d83d3daf9004a71a89f26e27d27ef6a16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'beberlei/assert' => array(
            'pretty_version' => 'v3.2.7',
            'version' => '3.2.7.0',
            'reference' => 'd63a6943fc4fd1a2aedb65994e3548715105abcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.8.15',
            'version' => '0.8.15.0',
            'reference' => '9b08d412b9da9455b210459ff71414de7e6241cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'caouecs/laravel-lang' => array(
            'pretty_version' => '6.0.2',
            'version' => '6.0.2.0',
            'reference' => '6769c655a02f77736e1d71d97b3f9e7986bb501b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../caouecs/laravel-lang',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.2.7',
            'version' => '1.2.7.0',
            'reference' => '95c63ab2117a72f48f5a55da9740a3273d45b7fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/composer' => array(
            'pretty_version' => '1.10.7',
            'version' => '1.10.7.0',
            'reference' => '956608ea4f7de9e58c53dfb019d85ae62b193c39',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => 'c6bea70230ef4dd483e6bbcab6005f682ed3a8de',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => '0c3e51e1880ca149682332770e25977c70cf9dae',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'reference' => 'fa2aaf99e2087f013a14f7432c1cd2dd7d8f1f51',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => 'v0.1.1',
            'version' => '0.1.1.0',
            'reference' => '8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.10.1',
            'version' => '1.10.1.0',
            'reference' => '35a4a70cd94e09e2259dfae7488afc6b474ecbd3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.10.2',
            'version' => '2.10.2.0',
            'reference' => 'aab745e7b6b2de3b47019da81e7225e14dcfdac8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '629572819973f13486371cb611386eb17851e85c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '9cf661f4eb38f7c881cac67c75ea9b00bf97b210',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'f350df0268e904597e3bd9c4685c53e0e333feea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'e864bbf5904cb8f5bb334f99209b48018522f042',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dragonmantank/cron-expression' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '72b6fbf76adb3cf5bc0db68559b33d41219aba27',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragonmantank/cron-expression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.17',
            'version' => '2.1.17.0',
            'reference' => 'ade6887fd9bd74177769645ab5c474824f8a418a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'facade/flare-client-php' => array(
            'pretty_version' => '1.3.2',
            'version' => '1.3.2.0',
            'reference' => 'db1e03426e7f9472c9ecd1092aff00f56aa6c004',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/flare-client-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'facade/ignition' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'reference' => 'e6bedc1e74507d584fbcb041ebe0f7f215109cf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'facade/ignition-contracts' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'f445db0fb86f48e205787b2592840dd9c80ded28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../facade/ignition-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'felixkiss/uniquewith-validator' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => '7ce4ff83c9003718e8febe1d4670eb869a720c5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../felixkiss/uniquewith-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fideloper/proxy' => array(
            'pretty_version' => '4.3.0',
            'version' => '4.3.0.0',
            'reference' => 'ec38ad69ee378a1eec04fb0e417a97cfaf7ed11a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fideloper/proxy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'filp/whoops' => array(
            'pretty_version' => '2.7.3',
            'version' => '2.7.3.0',
            'reference' => '5d5fe9bb3d656b514d455645b3addc5f7ba7714d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../filp/whoops',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'fruitcake/laravel-cors' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '1d127dbec313e2e227d65e0c483765d8d7559bf6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fruitcake/laravel-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'pretty_version' => 'v1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'fc10d778e4b84d5bd315dad194661e091d307c6f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fzaninotto/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.4',
            'version' => '6.5.4.0',
            'reference' => 'a4a1b6930528a8f7ee03518e6442ec7a44155d9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'a59da6cf61d80060647ff4d3eb2c03a2bc694646',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '239400de7a173fe9901b9ac7c06497751f00727a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '776503d3a8e85d4f9a1148614f95b7a608b046ad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'hekmatinasser/notowo' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'c51ad5dcedac966dd93ce558ac7e6a84e0020d6d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hekmatinasser/notowo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hekmatinasser/verta' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => '8659810fce313f49fd4f665ca9fb05a371aa6da7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hekmatinasser/verta',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/notifications' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/testing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v7.15.0',
            ),
        ),
        'ipecompany/smsirlaravel' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'reference' => 'eb28b1d88f06baa22c267a410f2c6a95002488a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ipecompany/smsirlaravel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jasonmccreary/laravel-test-assertions' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '3ead0117ce53d2b64ce6a6caa5db26f2188712ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasonmccreary/laravel-test-assertions',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'johnnyfreeman/laravel-custom-relation' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'f8fb2b19483e4e3cf4369cff94c5b135b64c0d94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../johnnyfreeman/laravel-custom-relation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.10',
            'version' => '5.2.10.0',
            'reference' => '2ba9c8c862ecd5510ed16c6340aa9f6eadb4f31b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'laravel/framework' => array(
            'pretty_version' => 'v7.15.0',
            'version' => '7.15.0.0',
            'reference' => '739c44a3f7041430a3fb357f2dcfdb78f55005d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/laravel' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '38491c5d5a2ad47452fea00e700f34964f13e48d',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/telescope' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '2e44c32c4e0b2442b118e73116582d1236b621f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/telescope',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/tinker' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'cde90a7335a2130a4488beb68f4b2141869241db',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/tinker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/ui' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'reference' => '15368c5328efb7ce94f35ca750acde9b496ab1b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/commonmark' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '412639f7cfbc0b31ad2455b2fe965095f66ae505',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/commonmark',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.0.69',
            'version' => '1.0.69.0',
            'reference' => '7106f78428a344bc4f643c233a94e48795f10967',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '6c6a7c533469873deacf998237e7649fc6b36223',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '38914429aac460e8e4616c8cb486ecb40ec90bb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'moontoast/math' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '5f47d34c87767dbcc08b30377a9827df71de91fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../moontoast/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'morilog/jalali' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => 'c3245cfdff201577cd54ae335953edd44f3f09c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../morilog/jalali',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.9.5',
            'version' => '1.9.5.0',
            'reference' => 'b2c28789e80a97badd14145fda39b545d83ca3ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.9.5',
            ),
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.59.1',
            'version' => '2.59.1.0',
            'reference' => 'a9000603ea337c8df16cc41f8b6be95a65f4d0f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.5.0',
            'version' => '4.5.0.0',
            'reference' => '53c2753d756f5adb586dca79c2ec0e2654dd9463',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nunomaduro/collision' => array(
            'pretty_version' => 'v4.2.0',
            'version' => '4.2.0.0',
            'reference' => 'd50490417eded97be300a92cd7df7badc37a9018',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/collision',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'opis/closure' => array(
            'pretty_version' => '3.5.4',
            'version' => '3.5.4.0',
            'reference' => '1d0deef692f66dae5d70663caee2867d0971306b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/closure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.99',
            'version' => '9.99.99.0',
            'reference' => '84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v1.13.0',
            'version' => '1.13.0.0',
            'reference' => 'bbade402cbe84c69b718120911506a3aa2bae653',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '45a2ec53a73c70ce41d55cedef9063630abaf1b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '6568f4687e5b41b054365f9ae03fcb1ed5f2069b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.1.0',
            'version' => '5.1.0.0',
            'reference' => 'cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '7462d5f123dfc080dfdf26897032a6513644fc95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.7.4',
            'version' => '1.7.4.0',
            'reference' => 'b2ada2ad5d8a32b89088b8adc31ecd2e3a13baf3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/bcmath_compat' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => '89cbb63742a32730b7187773a60b6b12b9db4479',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/bcmath_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.27',
            'version' => '2.0.27.0',
            'reference' => '34620af4df7d1988d8f0d7e91f6c8a3bf931d8dc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '7.0.10',
            'version' => '7.0.10.0',
            'reference' => 'f1884187926fbb755a9aaf0b3836ad3165b478bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '050bedf145a257b1ff02746c31894800e5122946',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => '1038454804406b0b5f5f520358e78c1c2f71501e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '995192df77f63a59e47f025390d2d1fdf8f425ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '8.5.5',
            'version' => '8.5.5.0',
            'reference' => '63dda3b212a0025d380a745f91bdb4d8c985adb7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '1.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.4',
            'version' => '0.10.4.0',
            'reference' => 'a8aec1b2981ab66882a01cce36a49b6317dc3560',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => 'v4.1.4',
            'version' => '4.1.4.0',
            'reference' => 'e75e5715e3b651ec20dee5844095aadefab81acb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '925ad8cf55ba7a3fc92e332c58fd0478ace3e1ca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'ba8fff1d3abb8bb4d35a135ed22a31c6ef3ede3d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.0.1',
            ),
        ),
        'rinvex/laravel-cacheable' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '4e2852d00134bfb3454d4373d093830291c0519d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rinvex/laravel-cacheable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rinvex/laravel-subscriptions' => array(
            'pretty_version' => 'v4.0.6',
            'version' => '4.0.6.0',
            'reference' => 'f54539dfc98dbfa54d59e28c563e981fd28ad1f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rinvex/laravel-subscriptions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rinvex/laravel-support' => array(
            'pretty_version' => 'v4.0.7',
            'version' => '4.0.7.0',
            'reference' => '67caadde0f1f9cce9890579ef649a758c5f8424c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rinvex/laravel-support',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'scrivo/highlight.php' => array(
            'pretty_version' => 'v9.18.1.1',
            'version' => '9.18.1.1',
            'reference' => '52fc21c99fd888e33aed4879e55a3646f8d40558',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scrivo/highlight.php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '5de4fc177adf9bce8df98d8d141a7559d7ccf6da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '720fcc7e9b5cf384ea68d9d930d480907a0c1a29',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '4.2.3',
            'version' => '4.2.3.0',
            'reference' => '464c90d7bdf5ad4e8a6aea15c091fec0603d4368',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '3.1.2',
            'version' => '3.1.2.0',
            'reference' => '68609e1261d215ea5b21b7987539cbfbe156ec3e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'edf8a461cf1d4005f19fb0b6b8b95a9f7fa0adc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '7cfd9e65d11ffb5af41198476395774d4c8a84c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '773f97c67f28de00d397be301821b06708fca0be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '4d7a795d35b889bf80a0cc04e08d77cedfa917a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '3aaaa15fa71d27650d62a948be022fe3b48541a3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'ff2aa5420bfbc296cf6a0bc785fa5b35736de7c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '8800503d56b9867d43d9c303b9cbcc26016e82f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'shetabit/multipay' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'reference' => '652492cec95b70e0968b5c6ffd196d07dbed049c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../shetabit/multipay',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'shetabit/payment' => array(
            'pretty_version' => 'v4.0.3',
            'version' => '4.0.3.0',
            'reference' => '310a45ef0317f15d70940feb44a9203d15d55498',
            'type' => 'library',
            'install_path' => __DIR__ . '/../shetabit/payment',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/eloquent-sortable' => array(
            'pretty_version' => '3.8.0',
            'version' => '3.8.0.0',
            'reference' => '5df5d545003f6443ced9684765759ea2e5cf5d91',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/eloquent-sortable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-schemaless-attributes' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'reference' => '2ad106215d7d4403e50cac0ca9aaea0bf91506c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-schemaless-attributes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-sluggable' => array(
            'pretty_version' => '2.4.2',
            'version' => '2.4.2.0',
            'reference' => '707265d4a29523a387e280e77f85071f04892540',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-sluggable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/laravel-translatable' => array(
            'pretty_version' => '4.3.2',
            'version' => '4.3.2.0',
            'reference' => 'c15b457ddce4ccaf174de652780647cb086a77a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-translatable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.2.3',
            'version' => '6.2.3.0',
            'reference' => '149cfdf118b169f7840bbe3ef0d4bc795d1780c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '0f0a271bc9b7d02a053d36fcdcb12662e2a8096e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'e544e24472d4c97b2d11ade7caacd446727c6bf9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'reference' => 'dd99cb3a0aff6cadd2a8d7d7ed72c2161e218337',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '7d0b927b9d3dc41d7d46cda38cbfcd20cdcbb896',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'cc0d059e2e997e79ca34125a52f3e33de4424ac7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'reference' => '405952c4e90941a17e52ef7489a2bd94870bb290',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '6e4320f06d5f2cce0d96530162491f4465179157',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '4298870062bfc667cb78d2b379be4bf5dec5f187',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'e0d853bddc2b2cfb0d67b0b4496c03fffe1d37fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '1151e5d51a680b22e758d05c6647dd9857503ec8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'c0c418f05e727606e85b482a8591519c4712cf45',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'e94c8b1bbe2bc77507a1056cdb06451c75b427f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'c4de7601eefbf25f9d47190abe07f79fe0a27424',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'e094b0770f7833fdf257e6ba4775be4e258230b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '3bff59ea7047e925be6b7f2059d60af31bb46d6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '1357b1d168eb7f68ad6a134838e46b0b159444a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'fa79b11539418b02fc5e1897267673ba2c19419c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'f048e612a3905f34931127360bdd2def19a5e582',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'a760d8964ff79ab9bf057613a5808284ec852ccc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '5e30b2799bc1ad68f7feb62b60a73743589438dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '7f6378c1fa2147eeb1b4c385856ce9de0d46ebd1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'reference' => '9d3e80d54d9ae747ad573cad796e8e247df7b796',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'bbd0ba121d623f66d165a55a108008968911f3eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'reference' => '66a8f0957a3ca54e4f724e49028ab19d75a8918b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'ac70459db781108db7c6d8981dd31ce0e29e3298',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => 'd387f07d4c15f9c09439cf3f13ddbe0b2c5e8be2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'reference' => 'e5ca07c8f817f865f618aa072c2fe8e0e637340e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.1.1',
            'version' => '5.1.1.0',
            'reference' => '46a942903059b0b05e601f00eb64179e05578c0f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '11336f6f84e16a720dae9d8e6ed5019efa85a0f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'reference' => 'dda2ee426acd6d801d5b7fd1001cde9b5f790e15',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v4.1.7',
            'version' => '4.1.7.0',
            'reference' => 'db63b2ea280fdcf13c4ca392121b0b2450b51193',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => 'e7f9bd5deff09a57318f9b900ab33a05acfcf4d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'watson/validating' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '861861a7c916d3e8bc4863d18b716cb0784a1a61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../watson/validating',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'ab2cb0b3b559010b75981b1bdce728da3ee90ad6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'zendframework/zend-diactoros' => array(
            'pretty_version' => '1.8.7',
            'version' => '1.8.7.0',
            'reference' => 'a85e67b86e9b8520d07e6415fcbcb8391b44a75b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zendframework/zend-diactoros',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
